### ISSUE TITLE
Create Temporary Course Database

### ISSUE THREAD

**Issue by abal274** [FatimahALhashim/no-line-up#6]
Should contain course name, course code, professor's name, description, term offered(winter/fall/summer), room number, time slot, day slot, prerequisites (separate table), capacity

**Comment by nelsonragel** [comment]
Created a temporary sql file please take a look

**Comment by nelsonragel** [comment]
references #5

**Comment by nelsonragel** [comment]
#5

**Comment by abal274** [comment]
close #6
